// Copyright (c) 2026 Ossama Mostafa
// MIT License

#include "GoldenRationDemo.h"

void GoldenRationDemo::init()
{
	//Vogel Equation Property sheet initialization
	ps_vogel.tb_topleft.x = 100;
	ps_vogel.tb_topleft.y = 100;
	ps_vogel.cl_height = 600;
	ps_vogel.cl_width = 600;
	ps_vogel.CalculateLayout();
	char title_vogel[] = { "Vogel Equation Property Sheet" };
	ps_vogel.setTitle(title_vogel, sizeof(title_vogel) / sizeof(char));
	ps_vogel.close();

	
	char iLabel[] = { "Number of Florets" };
	PS_Item imax(0,0, 1000, 1.00f, 200, 0, COLORREF(0xffffff), COLORREF(0x0a0a0a), iLabel, sizeof(iLabel) / sizeof(char));
	imax.bgColor = ps_vogel.cl_col;
	imax.textColor = 0xa0ffff;
	ps_vogel.Add_Item(imax);

	
	char scLabel[] = { "Scale" };
	PS_Item scmax(0,0, 100, 5.0, 200, 0, COLORREF(0xffffff), COLORREF(0x0a0a0a), scLabel, sizeof(scLabel) / sizeof(char));
	scmax.bgColor = ps_vogel.cl_col;
	scmax.textColor = 0xa0ffff;
	ps_vogel.Add_Item(scmax);

	
	char c1Label[] = { "Constant One" };
	PS_Item c1(0,0, 30, 1.00f, 100, 0, COLORREF(0xffffff), COLORREF(0x0a0a0a), c1Label, sizeof(c1Label) / sizeof(char));
	c1.bgColor = ps_vogel.cl_col;
	c1.textColor = 0xa0ffff;
	ps_vogel.Add_Item(c1);

	
	char c2Label[] = { "Constant Two" };
	PS_Item c2(0,0, 30, 1.00f, 100, 0, COLORREF(0xffffff), COLORREF(0x0a0a0a), c2Label, sizeof(c2Label) / sizeof(char));
	c2.bgColor = ps_vogel.cl_col;
	c2.textColor = 0xa0ffff;
	ps_vogel.Add_Item(c2);

	char colorsLabel[] = { "Colors" };
	PS_Item col(0, 0, 30, 1.00f, 100, 0, COLORREF(0xffffff), COLORREF(0x0a0a0a), colorsLabel, sizeof(colorsLabel) / sizeof(char));
	col.bgColor = ps_vogel.cl_col;
	col.textColor = 0xa0ffff;
	ps_vogel.Add_Item(col);


	//Info Window
	char infoTitle[] = { "Golden Ratio and the Vogel Equation" };
	myinfo = new InfoWindow(infoTitle, sizeof(infoTitle) / sizeof(char));
	myinfo->tb_topleft.x = 200;
	myinfo->tb_topleft.y = 100;
	myinfo->cl_height = 600;
	myinfo->cl_width = 600;
	myinfo->close();
	myinfo->CalculateLayout();

	char infoMessage[] = { "The golden ratio is an irrational number, denoted phi, which can be approximated by the ratio of Fibonacci numbers. The exact value of phi is (1+5^(1/2))/2. It's about 1.618. Fibonacci numbers are part of a sequence of numbers that start with 0, 1 and go on infinitely, each member of the sequence being equal to the sum of the previous two members. The golden ratio is interesting because many patterns in nature follow it. A certain logarithmic spiral, the golden spiral, can be generated by constructing golden rectangles. Sunflowers, pineapples, pinecones, nautilus shells are more examples of natural objects exhibiting fibonacci spirals and containing components that come in fibonacci numbers. For example sunflowers usually have 55, 89, or 144 petals, and spiral patterns in their seeds. \n\nIn 1979 Helmut Vogel came up with a mathematical equation to describe the geometry of sunflower seed patterns. In my demonstration, I've implemented Vogel's equation to draw circles. It's interesting to change constants and see the different patterns that come up, but with both constants set to 2 as it is intended, it does somewhat resemble a part of a sunflower. I used a polar coordinate system and calculate the angle for each floret. The index of this floret is used to calculate the radial distance of the floret from the center. I also multiply that result by a scaling factor which can be adjusted (as well as the constants and number of florets) in the property sheet.             \n\nThere are two basic ideas to explain why plant leaves or sunflower seeds grow in fibonacci spiral patterns. One theory is that it's to make the most efficient use of sun available for the plant. By growing at an angle of 137.5 degrees (the golden angle), more leaves can grow upward along the stem of the plant without shading the leaves below it. Another theory draws from mechanical and biochemical models. Both ideas generally agree that the reason it happens is to make the most efficient use of resources. Where they differ is which resource and what drives it. The latter model attributes the driving force to energy/electric forces and chemical hormones,\nlike auxin." };
	myinfo->AddPage(infoMessage, sizeof(infoMessage) / sizeof(char));
	myinfo->setMessagefromPage(0);
	


	//Picture window
	char root[] = { "./bitmaps/" };
	picWin.setRoot(root, sizeof(root) / sizeof(char));

	char picTitle[] = { "Pictures for Golden Ratio" };
	picWin.init(200, 100, 600, 600, picTitle, sizeof(picTitle) / sizeof(char));
	picWin.CalculateLayout();
	char ppath2[] = { "fibonacci_spiral.bmp" };
	char pic2_citation[] = { "A Fibonacci spiral constructed using golden rectangles along the pattern of the Fibonacci sequence." };
	picWin.AddSlide(ppath2, sizeof(ppath2) / sizeof(char), pic2_citation, sizeof(pic2_citation) / sizeof(char));
	char ppath[] = { "sunflower.bmp" };
	char pic1_citation[] = { "Sunflowers exhibit Fibonacci spirals and the number of those spirals is usually a Fibonacci number." }; 
	picWin.AddSlide(ppath, sizeof(ppath) / sizeof(char), pic1_citation, sizeof(pic1_citation) / sizeof(char));
	picWin.setPathfromSlide(0);
	char ppath3[] = { "pinecone.bmp" };
	char pic3_citation[] = { "The bracts of a pinecone arrange themselves in spirals along its axis." };
	picWin.AddSlide(ppath3, sizeof(ppath3) / sizeof(char), pic3_citation, sizeof(pic3_citation) / sizeof(char));
	char ppath4[] = { "nautilus_shell.bmp" };
	char pic4_citation[] = { "A nautilus, which is a type of mollusc, has a shell with fibonacci spirals." };
	picWin.AddSlide(ppath4, sizeof(ppath4) / sizeof(char), pic4_citation, sizeof(pic4_citation) / sizeof(char));
	char ppath5[] = { "sunflower_fibonacci.bmp" };
	char pic5_citation[] = { "A nautilus, which is a type of mollusc, has a shell with fibonacci spirals." };
	picWin.AddSlide(ppath5, sizeof(ppath5) / sizeof(char), pic5_citation, sizeof(pic5_citation) / sizeof(char));
	char ppath6[] = { "1024px-Indol-3-ylacetic_acid.bmp" };
	char pic6_citation[] = { "An auxin molecule, which is a plant growth hormone." };
	picWin.AddSlide(ppath6, sizeof(ppath6) / sizeof(char), pic6_citation, sizeof(pic6_citation) / sizeof(char));

	sli = new slide(); //initialize slide pointer













}
void GoldenRationDemo::updateVP()
{
	float v = 0;
	ps_vogel.get_item_value(0, &v);
	vp.i_max = v;
	ps_vogel.get_item_value(1, &v);
	vp.scale = v;
	ps_vogel.get_item_value(2, &v);
	vp.constantOne = v;
	ps_vogel.get_item_value(3, &v);
	vp.constantTwo = v;
	ps_vogel.get_item_value(4, &v);
	vp.colorson = v;
}
void GoldenRationDemo::DrawVogel(HDC hdc, HWND hwnd)
{
	RECT clirect;
	GetClientRect(hwnd, &clirect);
	POINT center;
	center.x = (clirect.right - clirect.left) / 2;
	center.y = (clirect.bottom - clirect.top) / 2;

	for (int i = numWindows - 1; i > -1; i--)
	{
		drawWindow(k[i], hdc, hwnd);
	}

	if (picWin.closed)
	{
		sli->drawPic = false;
	}


	DrawVogelEquation(center, hdc);

}

void GoldenRationDemo::drawWindow(int k, HDC hdc, HWND hwnd)
{
	if (k == 0)
	{
		ps_vogel.draw(hdc, hwnd);
	}
	if (k == 1)
	{
		myinfo->draw(hdc, hwnd);
	}
	if (k == 2)
	{
		picWin.draw(hdc, hwnd, sli);
	}
}



void GoldenRationDemo::DrawVogelEquation(POINT origin, HDC memdc)
{
	updateVP();
	COLORREF red = 0x0000dd;
	COLORREF green = 0x00dd00;
	COLORREF blue = 0xdd0000;
	COLORREF colors[3] = { red,green, blue };

	float phi = (1 + sqrt(5)) / 2;
	float phi_squared = pow(phi, vp.constantTwo);
	for (int i = 1; i < vp.i_max; i++)
	{

		HPEN blkPen = CreatePen(PS_SOLID, 2, 0x00aaab);
		HBRUSH brush = CreateSolidBrush(0x00aaab);
		if (vp.colorson == 1)
		{
			DeleteObject(blkPen);
			DeleteObject(brush);
			blkPen = CreatePen(PS_SOLID, 2, colors[i % 3]);
			brush = CreateSolidBrush(colors[i % 3]);

		}

		SelectObject(memdc, blkPen);		
		SelectObject(memdc, brush);
		float theta = vp.constantOne * 3.14159 * i / phi_squared;
		float r = vp.scale * sqrt(i);
		POINT curr;
		int dx = r * cos(theta);
		int dy = r * sin(theta);
		curr.x = origin.x + dx;
		curr.y = origin.y + dy;
		RECT floret;
		int floret_radius = 10;
		floret.left = curr.x - floret_radius;
		floret.right = curr.x + floret_radius;
		floret.top = curr.y - floret_radius;
		floret.bottom = curr.y + floret_radius;
		Ellipse(memdc, floret.left, floret.top, floret.right, floret.bottom);
		DeleteObject(brush);
		DeleteObject(blkPen);
	}
}
float GoldenRationDemo::vogel_equation(int floret_idx, int scale)
{
	float phi = (1 + sqrt(5)) / 2;
	float theta = 2 * 3.14159 * floret_idx / pow(phi, 2);
	return 0;
}



void GoldenRationDemo::open_propsheet()
{
	ps_vogel.open();
}
void GoldenRationDemo::open_info()
{
	myinfo->open();
}
void GoldenRationDemo::open_pic()
{
	picWin.open();
}
void GoldenRationDemo::processLclick(POINT cursor)
{
	if (ps_vogel.processClick(cursor) == 1)
	{		
		ps_vogel.selected = 1;
		myinfo->selected = 0;
		picWin.selected = 0;
		//floating the draw key of the selected window to the top so that the window will be drawn first
		int idx = -1;
		for (int i = 0; i < numWindows; i++)
		{
			if (k[i] == 0)
			{
				idx = i;
				break;
			}
		}
		for (int i = idx; i > 0; i--)
		{
			int temp = k[i];
			k[i] = k[i - 1];
			k[i - 1] = temp;
		}
	}
	else if (myinfo->processClick(cursor) == 1)
	{
		ps_vogel.selected = 0;
		myinfo->selected = 1;
		picWin.selected = 0;
		//floating the draw key of the selected window to the top so that the window will be drawn first
		int idx = -1;
		for (int i = 0; i < numWindows; i++)
		{
			if (k[i] == 1)
			{
				idx = i;
				break;
			}
		}
		for (int i = idx; i > 0; i--)
		{
			int temp = k[i];
			k[i] = k[i - 1];
			k[i - 1] = temp;
		}
	}
	else if (picWin.processClick(cursor) == 1)
	{
		ps_vogel.selected = 0;
		myinfo->selected = 0;
		picWin.selected = 1;
		//floating the draw key of the selected window to the top so that the window will be drawn first
		int idx = -1;
		for (int i = 0; i < numWindows; i++)
		{
			if (k[i] == 2)
			{
				idx = i;
				break;
			}
		}
		for (int i = idx; i > 0; i--)
		{
			int temp = k[i];
			k[i] = k[i - 1];
			k[i - 1] = temp;
		}
	}
}
void GoldenRationDemo::processDragging(POINT cursor)
{
	ps_vogel.processDragging(cursor);
	myinfo->processDragging(cursor);
	picWin.processDragging(cursor);
}
void GoldenRationDemo::processScroll(POINT pt, int zdelta, int mult)
{
	ps_vogel.processScroll(pt, zdelta, mult);
}
void GoldenRationDemo::endDrag()
{
	ps_vogel.endDragging();
	myinfo->endDragging();
	picWin.endDragging();
}

void GoldenRationDemo::cleanup()
{
	if (myinfo)
	{
		delete myinfo;
	}
}